# Generated by Django 4.2.26 on 2025-11-19 13:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_text', models.TextField(help_text='Original complaint text or audio transcript')),
                ('summary', models.TextField(blank=True, help_text='AI-generated 2-3 sentence summary')),
                ('category', models.CharField(choices=[('corruption', 'Corruption'), ('delay', 'Delay in Service Delivery'), ('bribery', 'Bribery'), ('misconduct', 'Misconduct'), ('lost_documents', 'Lost Documents'), ('infrastructure_damage', 'Infrastructure Damage'), ('other', 'Other')], default='other', max_length=50)),
                ('county', models.CharField(help_text='Kenyan county (e.g., Nairobi, Kisumu)', max_length=100)),
                ('urgency', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('sentiment', models.CharField(blank=True, help_text='Sentiment analysis result', max_length=50)),
                ('audio_file', models.FileField(blank=True, help_text='Voice recording (max 60 seconds)', null=True, upload_to='complaints/audio/')),
                ('image_file', models.ImageField(blank=True, help_text='Evidence image', null=True, upload_to='complaints/images/')),
                ('officer_name', models.CharField(blank=True, help_text='Name of officer involved (if mentioned)', max_length=200)),
                ('department_name', models.CharField(blank=True, help_text='Department involved (if mentioned)', max_length=200)),
                ('ai_processed', models.BooleanField(default=False, help_text='Whether AI processing has been completed')),
                ('is_verified', models.BooleanField(default=False, help_text='Whether complaint has been reviewed by admin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Complaint',
                'verbose_name_plural': 'Complaints',
                'ordering': ['-created_at'],
            },
        ),
    ]
