# Generated by Django 4.2.26 on 2025-11-23 11:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("complaints", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="complaint",
            name="is_anonymous",
            field=models.BooleanField(
                default=False,
                help_text="Whether this complaint was submitted anonymously",
            ),
        ),
        migrations.AddField(
            model_name="complaint",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="User who submitted (null if anonymous)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="complaints",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
